# Generated by Django 3.2.3 on 2021-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
