# Generated by Django 3.2.3 on 2021-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0002_auto_20210604_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
