# Generated by Django 3.2.5 on 2021-07-04 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0003_auto_20210704_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 4)),
        ),
    ]
