# Generated by Django 3.2.5 on 2021-07-04 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0004_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.date(2021, 7, 4)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating_website',
            field=models.IntegerField(default=0),
        ),
    ]
