# Generated by Django 3.2.3 on 2021-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0004_alter_contact_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
