# Generated by Django 3.2.5 on 2021-07-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0006_auto_20210703_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
